# Generated by Django 5.2 on 2025-04-12 02:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='audio',
            name='duration',
        ),
    ]
