# Generated by Django 5.2 on 2025-04-12 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_audiobook_genre_alter_audiobook_artist_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='audiobook',
            name='language',
            field=models.CharField(default='English', max_length=50),
        ),
    ]
