# Generated by Django 5.2 on 2025-04-12 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_audiobook_language'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audiobook',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
