# Generated by Django 5.2 on 2025-04-12 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_managers'),
    ]

    operations = [
        migrations.CreateModel(
            name='Audio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('artist', models.CharField(max_length=200)),
                ('audio_file', models.FileField(upload_to='audio_files/')),
                ('image', models.ImageField(blank=True, null=True, upload_to='audio_images/')),
                ('duration', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
