# Generated by Django 5.2 on 2025-04-12 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_picture',
            field=models.ImageField(blank=True, default='profile_pictures/default_profile_picture.jpg', null=True, upload_to='profile_pics/'),
        ),
    ]
