# Generated by Django 5.2 on 2025-04-12 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_profile_profile_picture'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='audiobooks_completed',
        ),
        migrations.AddField(
            model_name='profile',
            name='completed_audiobooks',
            field=models.IntegerField(default=0),
        ),
    ]
