# Generated by Django 5.2 on 2025-04-12 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_audiobook_language'),
        ('users', '0008_remove_profile_audiobooks_completed_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='current_streak',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='completed_audiobooks',
        ),
        migrations.AddField(
            model_name='profile',
            name='completed_audiobooks',
            field=models.ManyToManyField(blank=True, to='core.audiobook'),
        ),
    ]
