# Generated by Django 5.2 on 2025-04-12 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_remove_profile_current_streak_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='total_time_listened',
            new_name='total_listening_time',
        ),
        migrations.AddField(
            model_name='profile',
            name='current_streak',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
